export const GET_POKEMON_START = "GET_POKEMON_START";
export const GET_POKEMON_COMPLETE = "GET_POKEMON_COMPLETE";
export const GET_POKEMON_ERROR = "GET_POKEMON_ERROR";

export const GET_POKEMON_DETAIL_START = "GET_POKEMON_DETAIL_START";
export const GET_POKEMON_DETAIL_COMPLETE = "GET_POKEMON_DETAIL_COMPLETE";
export const GET_POKEMON_DETAIL_ERROR = "GET_POKEMON_DETAIL_ERROR";

export const GET_POKEMON_SPECIES_START = "GET_POKEMON_SPECIES_START";
export const GET_POKEMON_SPECIES_COMPLETE = "GET_POKEMON_SPECIES_COMPLETE";
export const GET_POKEMON_SPECIES_ERROR = "GET_POKEMON_SPECIES_ERROR";

export const ADD_MY_POKEMON = "ADD_MY_POKEMON";
export const RELEASE_POKEMON = "RELEASE_POKEMON";
export const RELEASE_ALL_POKEMON = "RELEASE_ALL_POKEMON";
